-- ═══════════════════════════════════════════════════════════════
-- 12_customer_interactions.sql — Customer interactions from email scan
-- Source: ibshi@ibs.com.vn Gmail inbox/sent (Chrome scan Apr 29, 2026)
-- Total: 33 interaction records
-- ═══════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('13fba58062d2b4', 'ce3934334dc841', 'SITE_VISIT', '2026-04-18', 'Braden Iberia factory visit', 'Ivan Martinez visited IBS factory. Discussed GHAZLAN suspension, HAJR final settlements, potential resume of works', 'FOLLOW_UP_NEEDED', 'Finalize GHAZLAN suspension cost proposal', '["Tony Hieu","Do Manh Hung"]', '["Ivan Martinez"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('6bbd7445448e51', 'ce3934334dc841', 'EMAIL', '2026-04-28', 'IBS financial information 2025 request', 'Braden Iberia requesting IBS financial information for 2025 - supplier assessment', 'FOLLOW_UP_NEEDED', 'Provide 2025 financial statements to Braden', '["IBS Admin"]', '["Ivan Martinez"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('6bec7c6dceb133', 'ce3934334dc841', 'EMAIL', '2026-04-28', 'GHAZLAN Project Suspension - no penalty confirmation', 'Confirmation letter received: no late delivery penalty for Units U1 U2 GHAZLAN 13105/13164', 'POSITIVE', NULL, '["Tony Hieu"]', '["Ivan Martinez"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('5b0f3e7840ad0c', 'ce3934334dc841', 'EMAIL', '2026-04-28', 'HAJR late delivery penalty risk 20%', 'Risk alert: Braden retaining 20% of final value per unit at 45% milestone invoices. Potential 20% late delivery penalty', 'NEGATIVE', 'Negotiate penalty reduction or waiver', '["IBS Admin"]', '["Ivan Martinez"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('f06ff0ccd66c36', 'ce3934334dc841', 'EMAIL', '2026-04-20', 'GHAZLAN Suspension - potential resume of works', 'Braden provided additional information on potential resume of works for GHAZLAN 13105/13164', 'POSITIVE', 'Prepare for production restart', '["Bao","Toan"]', '["Ivan Martinez"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('209e12f98c2857', 'bb8fc90583f843', 'EMAIL', '2026-04-23', 'Wisconsin PO 70923356 Shipment 3 final weight accepted', 'Acceptance of work for Shipment 3 signed by both parties. Final weight and final value confirmed', 'POSITIVE', 'Invoice Milestone 3', '["IBS Admin"]', '["Schneider Marcel"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('f6c8d4e8a3b577', 'bb8fc90583f843', 'EMAIL', '2026-04-17', 'Construction straps inquiry from WNC', 'WNC requesting IBS to quote supply of construction straps - spring no.55 size R/9 130mm FRIDAVO galvanised', 'FOLLOW_UP_NEEDED', 'Source construction straps from VN suppliers and provide quotation', '["Tony Hieu","IBS Admin"]', '["WNC Team"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('21cadd5fa17158', 'bb8fc90583f843', 'EMAIL', '2026-03-25', 'New RFQ - Steel Structure and Roof Panels 4451', 'WNC new RFQ for steel structure and roof panels. Delivery required Oct 2026', 'FOLLOW_UP_NEEDED', 'KTKH to prepare quotation', '["Tony Hieu","Sam"]', '["WNC Team"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('3025eede7c1837', '5b8a1ce4141c44', 'EMAIL', '2026-04-22', 'IBS HI capacity update shared with VPI', 'Capacity available and upcoming projects update sent to VPI/Matt Henning', 'POSITIVE', NULL, '["Tony Hieu","Paul"]', '["Matt Henning"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('bc53002234d6af', '5b8a1ce4141c44', 'EMAIL', '2026-04-15', 'Broadwing Carbon Capture ductwork quotation Rev.1', 'Q26.011 Rev.1 submitted for V6C899 Broadwing Carbon Capture ductwork', 'FOLLOW_UP_NEEDED', 'Await VOGT feedback on revised quotation', '["Paul Nguyen"]', '["Kyle (VPI)"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('65e73e68a125db', 'db8e68470f7f45', 'EMAIL', '2026-04-04', 'Allendale Phase 1c PO signed', 'PO BO000354/E120 Rev 1 signed. 8 tons ducting. PM assigned: Nguyen Bao Thu. 50% down payment invoiced', 'POSITIVE', 'Begin fabrication per communication matrix', '["Tony Hieu","DoTrongLuu"]', '["Bernhard Schmitt"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('3d6b76b00b4470', 'db8e68470f7f45', 'EMAIL', '2026-04-02', 'A1045 ducting and cyclones inquiry', 'New inquiry from Siempelkamp subsidiary for pneumatic ducting and cyclones A1045 project', 'FOLLOW_UP_NEEDED', 'Sam/Thanh to prepare quotation Q26.035', '["Tony Hieu","Sam","Thanh"]', '["Daniel Drack"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('65ea3bd7a2fc8d', 'db8e68470f7f45', 'EMAIL', '2026-03-11', 'BN000959 final settlement - IBS at 80% capacity', 'IBS confirmed operating at 80% workload capacity, able to accept new work', 'POSITIVE', 'Await Siempelkamp order placement', '["Tony Hieu"]', '["Bernhard Schmitt"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('232d671220c695', '6e72843f1524c4', 'EMAIL', '2026-04-22', 'FWS vessels quotation Q26.038 sent', 'Q26.038 Rev.0 sent to Gonnix for 03 filter vessels. Payment terms discussed', 'FOLLOW_UP_NEEDED', 'Await Gonnix feedback and project update', '["Paul Nguyen","Thanh"]', '["Nhat (Gonnix)"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('4164e25536973d', '6e72843f1524c4', 'EMAIL', '2026-02-07', '28 filter vessels painting contract draft', 'Draft contract for painting and cleaning 28 filter vessels submitted for internal approval', 'POSITIVE', 'Finalize contract signing', '["IBS Sales"]', '["Gonnix"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('52882400de7bdc', '15fc57e9695b49', 'EMAIL', '2026-04-14', 'Goodrich-TX Bypass Exhaust Q26.037', 'Quotation Q26.037 Rev.0 submitted for bypass exhaust systems', 'FOLLOW_UP_NEEDED', 'Await Bachmann feedback', '["Paul Nguyen"]', '["Mark Martel"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('0525cadd281b63', '15fc57e9695b49', 'EMAIL', '2026-02-25', 'Outlet Duct Dampers Q26.019', 'Quotation Q26.019 for outlet duct dampers with Corten material pricing confirmed', 'POSITIVE', 'Await order from Bachmann', '["Paul Nguyen"]', '["Matt","Mark"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('aa0d76bfce4bfc', '15fc57e9695b49', 'EMAIL', '2026-01-30', 'Bachmann Industries introduction and qualification', 'Bachmann exploring collaboration. IBS shared workload 2026-2027 and completed supplier qualification forms', 'POSITIVE', 'Continue bidding on Bachmann projects', '["Manh","Paul Nguyen"]', '["Bill","Mark Martel"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('216743fd19cf53', 'b8faee2239df4b', 'EMAIL', '2026-04-29', 'SCCD Slab quotation Q26.041 for Cebu-Mactan Bridge', 'Q26.041 quotation sent for steel-concrete composite deck slab for Cebu-Mactan Bridge project', 'FOLLOW_UP_NEEDED', 'Await Shinwa/Naoki feedback', '["Paul Nguyen","Tony Hieu"]', '["Naoki (Shinwa)"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('828d5f0f64e9f2', '908f6584e87848', 'EMAIL', '2026-03-13', 'Temporary Structures RFQ for Cebu-Mactan Bridge', 'Yokogawa Bridge Corp RFQ for temporary structures for Cebu-Mactan Bridge in Philippines', 'FOLLOW_UP_NEEDED', 'Prepare quotation for temporary structures', '["Tony Hieu"]', '["Hiep Pham (YBC)"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('a2e597eb0f0624', 'af142d441ee345', 'EMAIL', '2026-03-27', 'Bastrop HRSG project RFQ - very hot', 'John Cockerill GUIDI emphasized absolutely critical schedule for Bastrop NPP HRSG. Manufacturing area and load forecast 2026-2027 shared', 'POSITIVE', 'Prioritize Bastrop quotation - schedule critical', '["Paul Nguyen"]', '["GUIDI (JCE)"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('47de1217dc5827', 'd042862a8fd02a', 'EMAIL', '2026-02-25', 'Stein/Passer strategic partnership inquiry', 'Stein Arne Luraas (Purchase Manager, Passer Norway) exploring strategic fabrication partnership in Vietnam/Asia. Supplier qualification questionnaire and confidentiality agreement exchanged', 'FOLLOW_UP_NEEDED', 'Complete qualification process and explore first project', '["Tony Hieu","IBS Admin"]', '["Stein Arne Luraas"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('4f07c438195c4d', '8d8914c0bd4651', 'EMAIL', '2026-02-10', 'Tecnimont supplier qualification - Vietnam scouting', 'Tecnimont S.p.A. Jakarta conducting 2nd Vietnam scouting campaign. Supplier qualification package received', 'FOLLOW_UP_NEEDED', 'Complete Tecnimont supplier qualification', '["Bang","Tony Hieu"]', '["Tecnimont Jakarta"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('29240e297f7166', 'f07f1aab047d99', 'EMAIL', '2026-03-20', 'New barge construction inquiry', 'New customer inquiry for 176x44 deck cargo barge. Performance specifications and GA drawing received', 'FOLLOW_UP_NEEDED', 'Evaluate feasibility and prepare quotation', '["Tony Hieu","Bang"]', '["Capt. John"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('bf37916943df61', '61b6d13feb1460', 'EMAIL', '2026-04-24', 'Deaerator vessel quotation Q26.061', 'Q26.061 Rev.0 for deaerator pressure vessels with U-stamp for SUWTE Malaysia project sent to BS Deaerators', 'FOLLOW_UP_NEEDED', 'Await BS Deaerators feedback on quotation', '["Paul Nguyen"]', '["Richard Schacht"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('1de0f5d7d3f570', '834b4d064eeb76', 'EMAIL', '2026-04-02', 'Kanadevia VN steel structure contact', 'Kanadevia VN (Hitachi Zosen) requesting steel structure vendor info. Vendor Information Card submitted', 'FOLLOW_UP_NEEDED', 'Await Kanadevia project RFQ', '["Paul Nguyen","IBS Admin"]', '["Phuong HuynhThiLe"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('fca24898b4be29', 'b81454c120dfcb', 'EMAIL', '2026-04-07', 'UAE ASME/ABS PV inquiry', 'UAE customer interested in ASME DDC-U STAMP/PVHO-1/ABS certified pressure vessels for offshore/marine application', 'FOLLOW_UP_NEEDED', 'Prepare detailed quotation with ASME/ABS compliance', '["Paul Nguyen"]', '["Praphulla"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('1c0e11adfc8418', 'd3c91bfdc51dce', 'EMAIL', '2026-01-29', 'Iraq and Oman pressure vessel quotations', 'Q26.101 for Iraq Fuel Gas and Q26.100 for Oxy Oman VRU Mukhaizna sent', 'FOLLOW_UP_NEEDED', 'Await Hanas feedback on both quotations', '["Paul Nguyen"]', '["Hanas"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('ffa07b9f373312', 'a1fee7cc7fa549', 'EMAIL', '2026-04-06', 'Qatar Energy Urea rectangular ducts Q26.060', 'Q26.060 quotation for rectangular duct work for Qatar Energy Urea project submitted', 'FOLLOW_UP_NEEDED', 'Await feedback from Qatar contact', '["Paul Nguyen"]', '["Mr. Lee"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('d360ea1360ef75', 'e7afb9ebc5f545', 'EMAIL', '2025-12-29', 'Damen Song Cam supplier evaluation 2025', 'Damen Song Cam requesting supplier evaluation documents for 2025 assessment and 2026 procurement planning. Ship building processing capability shared', 'FOLLOW_UP_NEEDED', 'Submit complete supplier evaluation package', '["IBS Admin"]', '["Phong Pham Van"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('0f4cb2e9812426', '535f65ab04d944', 'EMAIL', '2025-11-13', 'Damen Marine Components rudder inquiry', 'DMC MD exploring alternative rudder manufacturing. NDA signed between DMC and IBS', 'FOLLOW_UP_NEEDED', 'Prepare rudder manufacturing capability assessment and quotation', '["Tony Hieu"]', '["Wiggert (DMC)"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('869cf27dcf13aa', 'da2242c845e540', 'EMAIL', '2026-03-19', 'Fermi Matador 3x Bypass Systems - urgent', 'Urgent fabrication request for 10025 Fermi Matador project - 3 bypass systems via Harald Swienty', 'FOLLOW_UP_NEEDED', 'Prioritize quotation response - urgent timeline', '["Paul Nguyen"]', '["Harald Swienty"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_customer_interactions (id, customer_id, interaction_type, interaction_date, subject, summary, outcome, next_action, attendees_ibs, attendees_customer, recorded_by, created_at) VALUES ('3ebc4bd209265f', '27f03ef90f33e4', 'EMAIL', '2026-04-17', 'Metso 8 ton column RFQ + supplier qualification', 'Metso RFQ for acid/elution columns Mt Bundy Gold Australia. IBS supplier capability questionnaire filled', 'FOLLOW_UP_NEEDED', 'Await Metso decision - lead time 24-26 weeks possible', '["Tony Hieu"]', '["Quang (Metso)","Igor","Valter"]', 'AI_IMPORT', datetime('now'));
