-- ═══════════════════════════════════════════════════════════════
-- 13_market_signals.sql — Market signals extracted from email analysis
-- Source: ibshi@ibs.com.vn email pattern analysis (Apr 29, 2026)
-- Total: 12 signal records
-- ═══════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('f8e6eb1bb5bd54', 'MARKET_EVENT', 'Tecnimont Vietnam scouting 2nd campaign', 'Tecnimont S.p.A. conducting 2nd supplier scouting campaign in Vietnam. Supplier qualification package sent to IBS', NULL, 'ibshi@ibs.com.vn email', 'Vietnam', 'energy', NULL, 0.8, 'HIGH', 'HRSG', '8d8914c0bd4651', NULL, '["energy", "HRSG", "Vietnam"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('87ca7bcb2bd4ea', 'MARKET_EVENT', 'Stein/Passer strategic partnership exploration', 'Norwegian company Passer AS exploring strategic fabrication partnership in Vietnam/Asia for heavy industry', NULL, 'ibshi@ibs.com.vn email', 'Norway/Asia', 'steel', NULL, 0.9, 'HIGH', 'OTHER', 'd042862a8fd02a', NULL, '["steel", "OTHER", "Norway/Asia"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('5d39ac625aa40b', 'MARKET_EVENT', 'Damen Marine Components alternative rudder sourcing', 'New MD of DMC looking for alternative rudder manufacturing capabilities outside traditional supply chain', NULL, 'ibshi@ibs.com.vn email', 'Netherlands', 'shipbuilding', 'Damen', 0.7, 'MEDIUM', 'SHIP', '535f65ab04d944', NULL, '["shipbuilding", "SHIP", "Netherlands"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('79ddf0366a3f2f', 'MARKET_EVENT', 'Kanadevia VN steel structure vendor scouting', 'Kanadevia VN (Hitachi Zosen) actively seeking steel structure vendors for Melaka and other projects', NULL, 'ibshi@ibs.com.vn email', 'Vietnam/Japan', 'steel', NULL, 0.7, 'MEDIUM', 'OTHER', '834b4d064eeb76', NULL, '["steel", "OTHER", "Vietnam/Japan"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('a77b23c02df22f', 'MARKET_EVENT', 'Bachmann Industries new partnership established', 'US-based Bachmann Industries completed supplier qualification with IBS - now actively sending RFQs for duct dampers and bypass systems', NULL, 'ibshi@ibs.com.vn email', 'USA', 'energy', NULL, 0.9, 'HIGH', 'DIVERTER', '15fc57e9695b49', NULL, '["energy", "DIVERTER", "USA"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('5b25d5cd958477', 'MARKET_EVENT', 'John Cockerill Bastrop HRSG - critical schedule', 'JCE Bastrop NPP project flagged as very hot with absolutely critical schedule. IBS submitted RFQ with manufacturing area and load forecast', NULL, 'ibshi@ibs.com.vn email', 'USA', 'energy', NULL, 0.95, 'CRITICAL', 'HRSG', 'af142d441ee345', NULL, '["energy", "HRSG", "USA"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('721de1229dfdfd', 'MARKET_EVENT', 'GHAZLAN project potential resume of works', 'Braden provided info on potential resume of GHAZLAN 13105/13164 after suspension. Would restart significant fabrication work for IBS', NULL, 'ibshi@ibs.com.vn email', 'Saudi Arabia', 'energy', 'Braden', 0.8, 'HIGH', 'DIVERTER', 'ce3934334dc841', NULL, '["energy", "DIVERTER", "Saudi Arabia"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('8f0d3b67ac1bd9', 'MARKET_EVENT', 'Middle East PV market demand - Iraq and Oman', 'Multiple RFQs from Middle East for pressure vessels: Iraq Fuel Gas inlet filter coalescer, Oxy Oman VRU Mukhaizna flare recovery', NULL, 'ibshi@ibs.com.vn email', 'Middle East', 'oil_gas', NULL, 0.7, 'MEDIUM', 'PV', 'd3c91bfdc51dce', NULL, '["oil_gas", "PV", "Middle East"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('76b1526fabd4ee', 'MARKET_EVENT', 'Carbon capture ductwork opportunity - VOGT Broadwing', 'VOGT V6C899 Broadwing Carbon Capture project ductwork RFQ - emerging green energy market segment', NULL, 'ibshi@ibs.com.vn email', 'USA', 'energy', NULL, 0.8, 'HIGH', 'DUCT', '5b8a1ce4141c44', NULL, '["energy", "DUCT", "USA"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('f8fa3f412e1e2f', 'MARKET_EVENT', 'Metso mining/mineral processing expansion to Vietnam sourcing', 'Metso sending multiple RFQs to IBS for columns (6t and 8t) for Australian mining projects. Supplier qualification completed', NULL, 'ibshi@ibs.com.vn email', 'Australia', 'mining', 'Metso', 0.75, 'HIGH', 'PV', '27f03ef90f33e4', NULL, '["mining", "PV", "Australia"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('ca49766e4da468', 'MARKET_EVENT', 'UAE offshore/marine PV market - ASME/ABS certified', 'UAE customer inquiring about ASME U-stamped and ABS certified pressure vessels for offshore/marine application - new market segment for IBS', NULL, 'ibshi@ibs.com.vn email', 'UAE', 'offshore', NULL, 0.65, 'MEDIUM', 'PV', 'b81454c120dfcb', NULL, '["offshore", "PV", "UAE"]', 'AI_IMPORT', datetime('now'));
INSERT OR IGNORE INTO sale_market_signals (id, signal_type, title, description, source_url, source_name, region, industry, competitor_name, relevance_score, impact_level, related_product_group, related_customer_id, expires_at, tags, created_by, created_at) VALUES ('e59f7269b64071', 'MARKET_EVENT', 'Cebu-Mactan Bridge megaproject - dual opportunities', 'Both Yokogawa Bridge and Shinwa engaged for Cebu-Mactan Bridge Philippines - temporary structures and SCCD slab quotations', NULL, 'ibshi@ibs.com.vn email', 'Philippines', 'infrastructure', NULL, 0.85, 'HIGH', 'OTHER', 'b8faee2239df4b', NULL, '["infrastructure", "OTHER", "Philippines"]', 'AI_IMPORT', datetime('now'));
